"""Themed document generation: Word, PDF, Excel and PowerPoint.

Every format is built from one neutral **document spec** so the chat answer
and the chaptered report engine share the same exporters::

    spec = {
        "title": "Q3 Staffing Report",
        "subtitle": "Generated by Larry",
        "sections": [
            {"heading": "Findings",
             "paragraphs": ["...", "..."],
             "bullets": ["...", "..."],
             "table": {"columns": ["name", "status"],
                        "rows": [["Alice", "Active"]]}},
        ],
    }

Styling comes from an admin-managed :class:`~ai_agent_core.models.DocumentTheme`
(colors, fonts, footer), applied consistently across all four formats.
Each exporter degrades gracefully: if its library is missing the format is
reported as unavailable instead of crashing.

Dependencies (all optional): python-docx, reportlab, openpyxl, python-pptx.
"""
from __future__ import annotations

import io
import re
from typing import Any, Dict, List, Optional, Tuple

FORMATS = {
    "word": ("docx", "application/vnd.openxmlformats-officedocument."
                     "wordprocessingml.document"),
    "pdf": ("pdf", "application/pdf"),
    "excel": ("xlsx", "application/vnd.openxmlformats-officedocument."
                      "spreadsheetml.sheet"),
    "ppt": ("pptx", "application/vnd.openxmlformats-officedocument."
                    "presentationml.presentation"),
}
ALIASES = {"docx": "word", "xlsx": "excel", "pptx": "ppt",
           "powerpoint": "ppt", "pdf": "pdf"}


def normalize_format(fmt: str) -> Optional[str]:
    fmt = (fmt or "").lower().strip()
    if fmt in FORMATS:
        return fmt
    return ALIASES.get(fmt)


class ThemeColors:
    """Resolved theme with safe fallbacks (works with theme=None)."""

    def __init__(self, theme=None):
        g = lambda attr, default: getattr(theme, attr, None) or default
        self.primary = self._hex(g("primary_color", "#1F4E79"))
        self.secondary = self._hex(g("secondary_color", "#2E75B6"))
        self.accent = self._hex(g("accent_color", "#C00000"))
        self.text = self._hex(g("text_color", "#1A1A24"))
        self.background = self._hex(g("background_color", "#FFFFFF"))
        self.heading_font = g("heading_font", "Calibri Light")
        self.body_font = g("body_font", "Calibri")
        self.footer_text = getattr(theme, "footer_text", "") or ""
        self.name = getattr(theme, "name", "") or "Default"

    @staticmethod
    def _hex(value: str) -> str:
        v = (value or "").lstrip("#")
        return v.upper() if re.fullmatch(r"[0-9a-fA-F]{6}", v) else "1F4E79"

    def rgb(self, hexstr: str) -> Tuple[int, int, int]:
        return tuple(int(hexstr[i:i + 2], 16) for i in (0, 2, 4))


def get_default_theme():
    from .models import DocumentTheme
    return DocumentTheme.objects.filter(is_active=True).order_by(
        "-is_default", "id").first()


def build_document(fmt: str, spec: Dict[str, Any],
                   theme=None) -> Tuple[bytes, str, str]:
    """Render ``spec`` to (bytes, content_type, extension).

    Raises ``ValueError`` for unknown formats and ``RuntimeError`` when the
    format's library is not installed.
    """
    key = normalize_format(fmt)
    if key is None:
        raise ValueError(f"Unknown document format {fmt!r}. "
                         f"Use one of: {', '.join(sorted(FORMATS))}.")
    colors = ThemeColors(theme if theme is not None else get_default_theme())
    builder = {"word": _build_docx, "pdf": _build_pdf,
               "excel": _build_xlsx, "ppt": _build_pptx}[key]
    data = builder(spec, colors)
    ext, ctype = FORMATS[key]
    return data, ctype, ext


# ---------------------------------------------------------------------------
# Word (.docx)
# ---------------------------------------------------------------------------

def _build_docx(spec, c: ThemeColors) -> bytes:
    try:
        from docx import Document
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.shared import Pt, RGBColor
    except ImportError as exc:
        raise RuntimeError("python-docx is not installed.") from exc

    doc = Document()
    for style_name, size, color in (("Title", 28, c.primary),
                                    ("Heading 1", 16, c.primary),
                                    ("Heading 2", 13, c.secondary)):
        st = doc.styles[style_name]
        st.font.name = c.heading_font
        st.font.size = Pt(size)
        st.font.color.rgb = RGBColor(*c.rgb(color))
    doc.styles["Normal"].font.name = c.body_font
    doc.styles["Normal"].font.size = Pt(11)
    doc.styles["Normal"].font.color.rgb = RGBColor(*c.rgb(c.text))

    doc.add_heading(spec.get("title") or "Document", 0)
    if spec.get("subtitle"):
        p = doc.add_paragraph(spec["subtitle"])
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        p.runs[0].font.color.rgb = RGBColor(*c.rgb(c.secondary))
        p.runs[0].font.italic = True

    for section in spec.get("sections", []):
        if section.get("heading"):
            doc.add_heading(section["heading"], level=1)
        for para in section.get("paragraphs", []):
            doc.add_paragraph(str(para))
        for bullet in section.get("bullets", []):
            doc.add_paragraph(str(bullet), style="List Bullet")
        table = section.get("table")
        if table and table.get("columns"):
            t = doc.add_table(rows=1, cols=len(table["columns"]))
            t.style = "Light Grid Accent 1"
            for i, col in enumerate(table["columns"]):
                cell = t.rows[0].cells[i]
                cell.text = str(col)
                for run in cell.paragraphs[0].runs:
                    run.font.bold = True
                    run.font.color.rgb = RGBColor(*c.rgb(c.primary))
            for row in table.get("rows", []):
                cells = t.add_row().cells
                for i, val in enumerate(row[:len(table["columns"])]):
                    cells[i].text = "" if val is None else str(val)

    if c.footer_text:
        footer_p = doc.sections[0].footer.paragraphs[0]
        footer_p.text = c.footer_text
        for run in footer_p.runs:
            run.font.size = Pt(8)
            run.font.color.rgb = RGBColor(*c.rgb(c.secondary))

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# PDF (.pdf)
# ---------------------------------------------------------------------------

def _build_pdf(spec, c: ThemeColors) -> bytes:
    try:
        from reportlab.lib import colors as rl_colors
        from reportlab.lib.pagesizes import LETTER
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import (ListFlowable, ListItem, Paragraph,
                                        SimpleDocTemplate, Spacer, Table,
                                        TableStyle)
    except ImportError as exc:
        raise RuntimeError("reportlab is not installed.") from exc

    def hx(h):  # "#RRGGBB"
        return rl_colors.HexColor("#" + h)

    buf = io.BytesIO()
    pdf = SimpleDocTemplate(buf, pagesize=LETTER,
                            title=spec.get("title") or "Document")
    base = getSampleStyleSheet()
    title_style = ParagraphStyle("T", parent=base["Title"],
                                 textColor=hx(c.primary))
    h1 = ParagraphStyle("H1", parent=base["Heading1"],
                        textColor=hx(c.primary))
    body = ParagraphStyle("B", parent=base["BodyText"],
                          textColor=hx(c.text))
    sub = ParagraphStyle("S", parent=base["Italic"],
                         textColor=hx(c.secondary))

    story = [Paragraph(spec.get("title") or "Document", title_style)]
    if spec.get("subtitle"):
        story.append(Paragraph(spec["subtitle"], sub))
    story.append(Spacer(1, 0.2 * inch))

    for section in spec.get("sections", []):
        if section.get("heading"):
            story.append(Paragraph(section["heading"], h1))
        for para in section.get("paragraphs", []):
            story.append(Paragraph(str(para), body))
        if section.get("bullets"):
            story.append(ListFlowable(
                [ListItem(Paragraph(str(b), body))
                 for b in section["bullets"]],
                bulletType="bullet"))
        table = section.get("table")
        if table and table.get("columns"):
            data = [[str(col) for col in table["columns"]]]
            data += [["" if v is None else str(v) for v in row]
                     for row in table.get("rows", [])]
            t = Table(data, hAlign="LEFT")
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), hx(c.primary)),
                ("TEXTCOLOR", (0, 0), (-1, 0), rl_colors.white),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.4, hx(c.secondary)),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                 [rl_colors.white, hx("F2F6FB")]),
            ]))
            story.append(Spacer(1, 0.1 * inch))
            story.append(t)
        story.append(Spacer(1, 0.15 * inch))

    def footer(canvas, doc_):
        if c.footer_text:
            canvas.saveState()
            canvas.setFont("Helvetica", 7)
            canvas.setFillColor(hx(c.secondary))
            canvas.drawString(0.8 * inch, 0.5 * inch, c.footer_text)
            canvas.drawRightString(LETTER[0] - 0.8 * inch, 0.5 * inch,
                                   f"Page {canvas.getPageNumber()}")
            canvas.restoreState()

    pdf.build(story, onFirstPage=footer, onLaterPages=footer)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Excel (.xlsx)
# ---------------------------------------------------------------------------

def _build_xlsx(spec, c: ThemeColors) -> bytes:
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Alignment, Font, PatternFill
        from openpyxl.utils import get_column_letter
    except ImportError as exc:
        raise RuntimeError("openpyxl is not installed.") from exc

    wb = Workbook()
    ws = wb.active
    ws.title = "Report"
    head_fill = PatternFill("solid", fgColor=c.primary)
    head_font = Font(bold=True, color="FFFFFF", name=c.body_font)
    title_font = Font(bold=True, size=16, color=c.primary,
                      name=c.heading_font)
    row_idx = 1
    ws.cell(row=row_idx, column=1, value=spec.get("title") or "Document"
            ).font = title_font
    row_idx += 2

    for section in spec.get("sections", []):
        if section.get("heading"):
            ws.cell(row=row_idx, column=1, value=section["heading"]).font = \
                Font(bold=True, size=12, color=c.secondary,
                     name=c.heading_font)
            row_idx += 1
        for para in section.get("paragraphs", []):
            ws.cell(row=row_idx, column=1, value=str(para)).alignment = \
                Alignment(wrap_text=True)
            row_idx += 1
        for bullet in section.get("bullets", []):
            ws.cell(row=row_idx, column=1, value=f"• {bullet}")
            row_idx += 1
        table = section.get("table")
        if table and table.get("columns"):
            for col_i, col in enumerate(table["columns"], start=1):
                cell = ws.cell(row=row_idx, column=col_i, value=str(col))
                cell.fill = head_fill
                cell.font = head_font
            row_idx += 1
            for row in table.get("rows", []):
                for col_i, val in enumerate(row, start=1):
                    ws.cell(row=row_idx, column=col_i,
                            value="" if val is None else str(val))
                row_idx += 1
        row_idx += 1

    for col_cells in ws.columns:
        width = max((len(str(cl.value)) for cl in col_cells if cl.value),
                    default=8)
        ws.column_dimensions[
            get_column_letter(col_cells[0].column)].width = min(width + 2, 60)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# PowerPoint (.pptx) — professional deck with custom theme
# ---------------------------------------------------------------------------

def _build_pptx(spec, c: ThemeColors) -> bytes:
    try:
        from pptx import Presentation
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
        from pptx.util import Emu, Inches, Pt
    except ImportError as exc:
        raise RuntimeError("python-pptx is not installed.") from exc

    prs = Presentation()
    prs.slide_width = Inches(13.333)   # 16:9 widescreen
    prs.slide_height = Inches(7.5)
    BLANK = prs.slide_layouts[6]
    W, H = prs.slide_width, prs.slide_height

    def bg(slide, hexstr):
        slide.background.fill.solid()
        slide.background.fill.fore_color.rgb = RGBColor(*c.rgb(hexstr))

    def accent_bar(slide, top, height=Inches(0.12), color=None):
        from pptx.enum.shapes import MSO_SHAPE
        bar = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, top, W, height)
        bar.fill.solid()
        bar.fill.fore_color.rgb = RGBColor(*c.rgb(color or c.accent))
        bar.line.fill.background()
        return bar

    def textbox(slide, left, top, width, height, text, size, color,
                bold=False, font=None, align=PP_ALIGN.LEFT):
        box = slide.shapes.add_textbox(left, top, width, height)
        tf = box.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.alignment = align
        run = p.add_run()
        run.text = text
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.name = font or c.heading_font
        run.font.color.rgb = RGBColor(*c.rgb(color))
        return box

    def footer(slide, number):
        if c.footer_text:
            textbox(slide, Inches(0.5), H - Inches(0.45), W - Inches(2),
                    Inches(0.35), c.footer_text, 9, c.secondary,
                    font=c.body_font)
        textbox(slide, W - Inches(1.2), H - Inches(0.45), Inches(0.8),
                Inches(0.35), str(number), 9, c.secondary,
                font=c.body_font, align=PP_ALIGN.RIGHT)

    # ---- title slide -------------------------------------------------------
    slide = prs.slides.add_slide(BLANK)
    bg(slide, c.primary)
    accent_bar(slide, int(H * 0.62))
    textbox(slide, Inches(0.9), int(H * 0.30), W - Inches(1.8), Inches(1.6),
            spec.get("title") or "Presentation", 40, "FFFFFF", bold=True)
    if spec.get("subtitle"):
        textbox(slide, Inches(0.9), int(H * 0.66), W - Inches(1.8),
                Inches(0.8), spec["subtitle"], 18, "DCE6F2",
                font=c.body_font)
    footer(slide, 1)

    # ---- agenda slide ------------------------------------------------------
    sections = spec.get("sections", [])
    headings = [s.get("heading") for s in sections if s.get("heading")]
    slide_no = 1
    if len(headings) > 1:
        slide_no += 1
        slide = prs.slides.add_slide(BLANK)
        bg(slide, c.background)
        accent_bar(slide, Inches(1.05), Inches(0.06), c.primary)
        textbox(slide, Inches(0.7), Inches(0.35), W - Inches(1.4),
                Inches(0.7), "Agenda", 28, c.primary, bold=True)
        box = slide.shapes.add_textbox(Inches(1.0), Inches(1.5),
                                       W - Inches(2.0), H - Inches(2.4))
        tf = box.text_frame
        tf.word_wrap = True
        for i, hname in enumerate(headings):
            p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            run = p.add_run()
            run.text = f"{i + 1}.  {hname}"
            run.font.size = Pt(18)
            run.font.name = c.body_font
            run.font.color.rgb = RGBColor(*c.rgb(c.text))
            p.space_after = Pt(10)
        footer(slide, slide_no)

    # ---- content slides ----------------------------------------------------
    for section in sections:
        slide_no += 1
        slide = prs.slides.add_slide(BLANK)
        bg(slide, c.background)
        accent_bar(slide, Inches(1.05), Inches(0.06), c.primary)
        textbox(slide, Inches(0.7), Inches(0.35), W - Inches(1.4),
                Inches(0.7), section.get("heading") or "", 26, c.primary,
                bold=True)

        content_top = Inches(1.45)
        texts = ([str(p) for p in section.get("paragraphs", [])] +
                 [f"• {b}" for b in section.get("bullets", [])])
        if texts:
            box = slide.shapes.add_textbox(Inches(0.8), content_top,
                                           W - Inches(1.6), Inches(2.6))
            tf = box.text_frame
            tf.word_wrap = True
            for i, text in enumerate(texts[:8]):
                p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
                run = p.add_run()
                run.text = text[:220]
                run.font.size = Pt(14)
                run.font.name = c.body_font
                run.font.color.rgb = RGBColor(*c.rgb(c.text))
                p.space_after = Pt(6)
            content_top = content_top + Inches(0.35 * min(len(texts), 8))

        table = section.get("table")
        if table and table.get("columns"):
            cols = table["columns"][:6]
            rows = table.get("rows", [])[:8]
            t_shape = slide.shapes.add_table(
                len(rows) + 1, len(cols), Inches(0.8),
                min(content_top + Inches(0.2), H - Inches(2.2)),
                W - Inches(1.6),
                Inches(0.4) * (len(rows) + 1)).table
            for i, col in enumerate(cols):
                cell = t_shape.cell(0, i)
                cell.text = str(col)
                cell.fill.solid()
                cell.fill.fore_color.rgb = RGBColor(*c.rgb(c.primary))
                for p in cell.text_frame.paragraphs:
                    for run in p.runs:
                        run.font.size = Pt(12)
                        run.font.bold = True
                        run.font.color.rgb = RGBColor(255, 255, 255)
                        run.font.name = c.body_font
            for r_i, row in enumerate(rows, start=1):
                for c_i, val in enumerate(row[:len(cols)]):
                    cell = t_shape.cell(r_i, c_i)
                    cell.text = "" if val is None else str(val)[:60]
                    for p in cell.text_frame.paragraphs:
                        for run in p.runs:
                            run.font.size = Pt(11)
                            run.font.name = c.body_font
                            run.font.color.rgb = RGBColor(*c.rgb(c.text))
        footer(slide, slide_no)

    # ---- closing slide -----------------------------------------------------
    slide = prs.slides.add_slide(BLANK)
    bg(slide, c.primary)
    accent_bar(slide, int(H * 0.55))
    textbox(slide, Inches(0.9), int(H * 0.38), W - Inches(1.8), Inches(1.2),
            "Thank you", 36, "FFFFFF", bold=True)
    footer(slide, slide_no + 1)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Spec builders (chat answers and chaptered reports -> document spec)
# ---------------------------------------------------------------------------

def spec_from_chat(message: str, reply: str,
                   results: List[Dict[str, Any]], bot=None) -> Dict[str, Any]:
    sections: List[Dict[str, Any]] = [{
        "heading": "Answer",
        "paragraphs": [p for p in reply.split("\n") if p.strip()],
    }]
    for block in results:
        rows = block.get("rows", [])
        columns = list(rows[0].keys()) if rows else []
        sections.append({
            "heading": f"Data: {block['table']}",
            "table": {"columns": columns,
                      "rows": [[r.get(col) for col in columns]
                               for r in rows]},
        })
    return {"title": message[:120].strip() or "Chat answer",
            "subtitle": f"Generated by {getattr(bot, 'name', 'Assistant')}",
            "sections": sections}


def spec_from_report(job) -> Dict[str, Any]:
    sections = []
    for ch in job.chapters.all():
        paragraphs, bullets = [], []
        for line in (ch.content or "").split("\n"):
            line = line.strip()
            if not line:
                continue
            if line.startswith(("- ", "• ")):
                bullets.append(line[2:].strip())
            else:
                paragraphs.append(line)
        sections.append({
            "heading": f"Chapter {ch.index}: {ch.title}",
            "paragraphs": paragraphs,
            "bullets": bullets,
        })
    return {"title": job.title,
            "subtitle": f"Requested: {job.request_text[:140]}",
            "sections": sections}
