# Generated by Django 4.2.30 on 2026-09-11 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(help_text="Django app label of the target table (e.g. 'Req_tracker').", max_length=100)),
                ('model_name', models.CharField(help_text="Model class name exactly as in the legacy allowlist (e.g. 'Requistion').", max_length=100)),
                ('applies_to_all_authenticated', models.BooleanField(default=False, help_text='If set, the policy matches every authenticated user regardless of group membership.')),
                ('access_level', models.CharField(choices=[('read', 'Read (fetch + aggregate)'), ('aggregate_only', 'Aggregate only (no row-level reads)'), ('deny', 'Deny')], default='read', max_length=20)),
                ('allowed_fields', models.JSONField(blank=True, default=list, help_text='Optional JSON list narrowing the legacy field allowlist for this audience (empty = every legacy-allowed field). Must be a subset of the legacy allowlist.')),
                ('max_rows_per_call', models.PositiveIntegerField(blank=True, help_text='Optional per-call row cap for this audience (further clamped by the legacy MAX_LIMIT).', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority policies are evaluated first.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text="Groups this policy applies to. Leave empty and tick 'applies to all authenticated' for a global policy.", related_name='table_access_policies', to='auth.group')),
            ],
            options={
                'verbose_name': 'table access policy',
                'verbose_name_plural': 'table access policies',
                'ordering': ['-priority', 'app_label', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='TableAccessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('model_path', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('fetch', 'Fetch rows'), ('aggregate', 'Aggregate'), ('describe', 'Describe model'), ('list', 'List models')], max_length=20)),
                ('was_allowed', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('query', models.JSONField(blank=True, default=dict)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_agent_core.tableaccesspolicy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_access_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tableaccesspolicy',
            index=models.Index(fields=['app_label', 'model_name', 'is_active'], name='ai_agent_co_app_lab_c912f9_idx'),
        ),
    ]
