# Generated by Django 4.2.30 on 2026-09-11 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_agent_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Assistant', max_length=80)),
                ('avatar_emoji', models.CharField(default='🤖', help_text='Emoji shown on the launcher icon (ignored if an image URL is set).', max_length=8)),
                ('avatar_image_url', models.URLField(blank=True, help_text='Optional image URL for the launcher/avatar.')),
                ('greeting', models.CharField(default='Hi! Ask me anything about your data.', help_text='First message shown when the chat opens.', max_length=255)),
                ('personality', models.TextField(blank=True, help_text='Free-text persona description; passed to the LLM handler and merged over the file-based profile.')),
                ('system_prompt', models.TextField(blank=True, help_text='Optional system prompt override for the LLM handler.')),
                ('window_mode', models.CharField(choices=[('right', 'Docked right'), ('left', 'Docked left'), ('popup', 'Centered popup')], default='right', help_text='Where the chat window appears: docked left, docked right, or a centered popup.', max_length=10)),
                ('primary_color', models.CharField(default='#2563eb', help_text='Hex accent color for the widget.', max_length=7)),
                ('placeholder_text', models.CharField(default='Type a question…', max_length=120)),
                ('show_result_cards', models.BooleanField(default=True, help_text='Render matching rows as cards under the bot reply.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='The default profile rendered by {% ai_bot_widget %}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SearchableTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, help_text='Shown to the LLM/agent as table context.', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['app_label', 'model_name'],
                'unique_together': {('app_label', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='BotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('bot_name', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BotChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('content', models.TextField()),
                ('results', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_agent_core.botconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='Empty = visible to everyone with table access; otherwise only these groups see this field.', related_name='visible_search_fields', to='auth.group')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='ai_agent_core.searchabletable')),
            ],
            options={
                'ordering': ['table', 'field_name'],
                'unique_together': {('table', 'field_name')},
            },
        ),
    ]
