# Generated by Django 4.2.30 on 2026-09-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent_core', '0002_botprofile_searchabletable_botconversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botprofile',
            name='avatar_emoji',
            field=models.CharField(blank=True, default='', help_text='Optional emoji launcher. Leave BLANK to use the built-in animated robot SVG (recommended). Ignored if an image URL is set.', max_length=8),
        ),
    ]
