# Generated by Django 4.2.30 on 2026-09-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent_core', '0003_alter_botprofile_avatar_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='theme_mode',
            field=models.CharField(choices=[('auto', 'Auto (follow site / OS dark mode)'), ('light', 'Always light'), ('dark', 'Always dark')], default='auto', help_text="Auto detects the host page's dark/light mode (data-theme / data-bs-theme / 'dark' class on <html>/<body>) and falls back to the OS prefers-color-scheme; or force one theme.", max_length=10),
        ),
    ]
