# Generated by Django 4.2.30 on 2026-09-11 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_agent_core', '0004_botprofile_theme_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('request_text', models.TextField(help_text="The user's original report request.")),
                ('status', models.CharField(choices=[('pending', 'Pending (outline not started)'), ('writing', 'Writing chapters'), ('done', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('total_chapters', models.PositiveIntegerField(default=0)),
                ('chapters_done', models.PositiveIntegerField(default=0)),
                ('progress_note', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_jobs', to='ai_agent_core.botconversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('brief', models.TextField(blank=True, help_text='One-line outline brief for this chapter.')),
                ('content', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True, help_text="Short summary carried into later chapters' prompts instead of the full text (keeps context small).")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('writing', 'Writing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='ai_agent_core.reportjob')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('job', 'index')},
            },
        ),
    ]
