# Generated by Django 4.2.30 on 2026-09-11 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_agent_core', '0005_reportjob_reportchapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('primary_color', models.CharField(default='#1F4E79', help_text='Hex. Title slides, headings, table header fills.', max_length=7)),
                ('secondary_color', models.CharField(default='#2E75B6', help_text='Hex. Subheadings, footers, table grid lines.', max_length=7)),
                ('accent_color', models.CharField(default='#C00000', help_text='Hex. PowerPoint accent bars and highlights.', max_length=7)),
                ('text_color', models.CharField(default='#1A1A24', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Hex. Slide background (PowerPoint).', max_length=7)),
                ('heading_font', models.CharField(default='Calibri Light', max_length=60)),
                ('body_font', models.CharField(default='Calibri', max_length=60)),
                ('footer_text', models.CharField(blank=True, help_text='Shown in document footers / slide footers.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Used when no theme is specified.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('fmt', models.CharField(max_length=10)),
                ('filename', models.CharField(max_length=220)),
                ('content_type', models.CharField(max_length=120)),
                ('data', models.BinaryField()),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_agent_core.documenttheme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
