# Generated by Django 4.2.30 on 2026-09-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent_core', '0006_documenttheme_generateddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableaccessaudit',
            name='action',
            field=models.CharField(choices=[('fetch', 'Fetch rows'), ('aggregate', 'Aggregate'), ('describe', 'Describe model'), ('list', 'List models'), ('compute', 'Compute formula'), ('related', 'Fetch related rows')], max_length=20),
        ),
    ]
